# config/drone_goal.yaml
# file path is load bearing ^

default_settings:
  trainer_type: ppo
  hyperparameters:
    batch_size: 2048
    buffer_size: 40960
    learning_rate: 3.0e-4
    beta: 5.0e-3
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    learning_rate_schedule: linear
  network_settings:
    normalize: true
    hidden_units: 256
    num_layers: 3
    vis_encode_type: simple
  reward_signals:
    extrinsic:
      gamma: 0.995
      strength: 1.0
  time_horizon: 128
  max_steps: 3.0e6
  summary_freq: 10000

behaviors:
  drone_goal: {}
  # leaving this {} empty causes Unity to use default_settings ^